### ISSUE TITLE
Version of repo that doesn't transform jsx

### ISSUE THREAD

**Issue by morenoh149** [danvk/mocha-react#6]
Is there a version of this repo that doesn't do the jsx transformation? I'm running react on rails
and the jsx transformation is already being performed for me by the https://github.com/reactjs/react-rails gem.

**Comment by danvk** [comment]
The JSX transformation is idempotent, i.e. it shouldn't hurt to run it twice. Are you concerned about performance?

**Comment by morenoh149** [comment]
nope. Didn't know it was idempotent. Thanks.

Actually I was running into issues with the transformation. Hence why I wanted to disable it. I'm actually just going to give up on testing my project for now. Burned 3 days on this topic. React + Rails = not ready bro
